name:                dist-sys-challenge-haskell
version:             0.1.0.0
github:              "mattysmith22/dist-sys-challenge-haskell"
license:             BSD3
author:              "Matthew Smith"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mattysmith22/dist-sys-challenge-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  challenge-1:
    main:                Main.hs
    source-dirs:         challenge-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dist-sys-challenge-haskell

tests:
  dist-sys-challenge-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dist-sys-challenge-haskell
